# Generated by Django 3.1.6 on 2021-04-10 14:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Name')),
                ('age', models.IntegerField(default=0, verbose_name='Age')),
                ('gender', models.CharField(default='', max_length=20, verbose_name='Gender')),
                ('username', models.CharField(default='', max_length=15, unique=True, verbose_name='Username')),
                ('nationality', models.CharField(default='', max_length=30, verbose_name='Nationality')),
                ('height', models.CharField(default=0, max_length=15, verbose_name='Height')),
                ('hair_color', models.CharField(default='', max_length=20, verbose_name='Hair Color')),
                ('bio', models.TextField(default='', max_length=5000, verbose_name='Bio')),
                ('occupation', models.CharField(default='', max_length=50, verbose_name='Occupation')),
                ('address', models.TextField(default='', max_length=300, verbose_name='Address')),
                ('image', models.ImageField(upload_to='media/Image', verbose_name='Image')),
                ('social', models.TextField(default='', max_length=5000, verbose_name='Social Links')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
